/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "m_pd.h"

static t_class *broadcastsend_class;

typedef struct _broadcastsend {
   t_object x_obj;
   t_int port;
   t_int socket;
   struct sockaddr_in their_addr; // connector's address information
} t_broadcastsend;

// ------------- SEND ANYTHING
void broadcastsend_message_anything_method(t_broadcastsend *x, t_symbol *s, int argc, t_atom *argv){
   t_binbuf *b = binbuf_new();
   char *buf;
   int length;
   t_atom message;
   SETSYMBOL(&message, s);
   binbuf_add(b, 1, &message); // message name
   binbuf_add(b, argc, argv); // message parameters
   binbuf_gettext(b, &buf, &length);
   int size = sendto(x->socket, buf, length, 0,(struct sockaddr *) &x->their_addr, sizeof(x->their_addr));
   (void) size;
}

void broadcastsend_create_sender(t_broadcastsend *x) {
   int broadcast = 1;

   if ((x->socket = socket(AF_INET, SOCK_DGRAM, 0)) == -1) {
      post("Problems creating socket");
   }

   if (setsockopt(x->socket, SOL_SOCKET, SO_BROADCAST, &broadcast,sizeof broadcast) == -1) {
      post("Problem in setsockopt (SO_BROADCAST)");
   }
   x->their_addr.sin_family = AF_INET;    // host byte order
   x->their_addr.sin_port = htons(x->port); // short, network byte order
   x->their_addr.sin_addr.s_addr = INADDR_BROADCAST;
   memset(x->their_addr.sin_zero, '\0', sizeof(x->their_addr.sin_zero));

}

// Constructor of the class
void * broadcastsend_new(t_floatarg port) {
   t_broadcastsend *x = (t_broadcastsend *) pd_new(broadcastsend_class);
   if(port != 0)
      x->port = port;
   else
      x->port = 40000;
   broadcastsend_create_sender(x);
   return (void *) x;
}

// Destroy the class
void broadcastsend_destroy(t_broadcastsend *x) {
   if(x->socket > 0)
      close(x->socket);
   post("You say good bye and I say hello");
}

void broadcastsend_setup(void) {
   broadcastsend_class = class_new(gensym("broadcastsend"),
      (t_newmethod) broadcastsend_new, // Constructor
      (t_method) broadcastsend_destroy, // Destructor
      sizeof (t_broadcastsend),
      CLASS_DEFAULT,
      A_DEFFLOAT,
      0);//Must always ends with a zero

   class_addanything(broadcastsend_class, broadcastsend_message_anything_method);
}
